apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mytestchart1.fullname" . }}-mongodb
  namespace: {{ .Values.mongodb.namespace }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  serviceName: {{ include "mytestchart1.fullname" . }}-mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          resources:
            limits:
              cpu: "{{ .Values.mongodb.resources.limits.cpu }}"
              memory: "{{ .Values.mongodb.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.mongodb.resources.requests.cpu }}"
              memory: "{{ .Values.mongodb.resources.requests.memory }}"
