# Default values for mytestchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
createNamespace: true
namespaceName: "data-pg" # Set the default namespace name

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
 - name: ecr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "" # Leave empty to generate a name using the fullname template

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

tolerations: []

affinity: {}

nodeSelector:
  gpu: "true"

mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
