# templates/efs.yaml

{{- if .Values.efs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-efs
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.efs.storageSize }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-efs-pv
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.efs.storageSize }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.efs.server }}
    path: {{ .Values.efs.path }}
{{- end }}
