# templates/service.yaml

{{- include "my-helm-chart.namespace" . | nindent 2 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}  # Reference the namespace here
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-helm-chart.selectorLabels" . | nindent 4 }}
