# templates/serviceaccount.yaml

{{- include "my-helm-chart.namespace" . | nindent 2 }}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-helm-chart.serviceAccountName" . }}
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}  # Reference the namespace here
{{- end }}
